### ISSUE TITLE
Need some help for downloading sounddr_data

### ISSUE THREAD

**Issue by Jingnin-S** [ReML-AI/Sound-Dr#1]
When I click the link to download the dataset"sounddr_data_passwordFPT_Software.zip", it needs a password to extract the zip. Could you please share the password with me? Thanks！

**Comment by Jingnin-S** [comment]
Sorry， I found the password. It's my oversight. I am sorry to trouble you.

**Comment by darthgween** [comment]
Can you help me to find the password?

**Comment by darthgween** [comment]
@James-yin-amd

**Comment by hvt1609** [comment]
Sorry for being unclear,
 try: FPT_Software
